### PR TITLE
add bower and grunt for developing and testing themes

### PR DESCRIPTION
**Pull request by btfou**
Setup for adding flat theme.

Concept is each new theme is added to `dijit/themes` folder, and added to `.gitignore`. Use bower to install dojo and dijit locally to develop and test themes.

Themes would always use common `dijit.css` and `dijit_rtl.css` from dijit.

### CODE REVIEW

**Comment by btfou** [comment]
@dylans Not sure what the profile should include. This is just dijit's. Please advise.

**Comment by dylans** [comment]
@btfou The main purpose of it is so if someone runs a build, it won't try to treat things that aren't AMD as AMD. We really only need it if we add a chart theme to match the flat theme, which would then be an AMD module (which I think was part of the plan). I'll add some comments inline.

**Comment by btfou** [comment]
@dylans here's flat theme restructured with a few minor changes as noted in README. Editor icons still need added.

**Comment by dylans** [comment]
Closed via e4eab64, thanks for the clean-up efforts!

**Pull request closed without merging**
