### PR TITLE
add updated icons

### PR DESCRIPTION
**Pull request by btfou**
- adds updated icon fonts;
- improved icon names and hex code/icon order;
- uses a single css file for all icons, including `.dijitIcon*` and `.dijitEditorIcon*` aliases and rtl,
- includes `selection.json` which can be used to update the icon set using https://icomoon.io/app;
- adds icons to the theme dev/test app.

NOTE: This icon set is incomplete. Many of the `.dijitIcon*` and `.dijitEditorIcon*` icons do not have suitable icons in the Google icon set. These icons have a placeholder and have been assigned hex codes. Instead of using icons which do not quite fit the use, or from different icon sets, SVGs for these icons need to be created and added to the font. The SVGs need to be created on a 24 x 24 grid and generally be of the same design as the other icons.

### CODE REVIEW

**Comment by wkeese** [comment]
Exciting to use font icons.   I guess this only works on IE9+?

Too bad, but not surprising, that the Google icon set doesn't cover the editor icons, although I'm surprised the other icons aren't covered.   Actually, I think there might be some confusion; ISTM that most of the icons in [commonIconsObjActEnabled.png](https://github.com/dojo/dijit/blob/master/icons/images/commonIconsObjActEnabled.png) don't appear in any dijit controls.  IIRC the only icons dijit actually uses are the arrows and the X for closing a dialog box.  (I'm not sure why that  [commonIconsObjActEnabled.png](https://github.com/dojo/dijit/blob/master/icons/images/commonIconsObjActEnabled.png) sprite has so many icons).

PS: Oh, and the ! icon for an invalid text box.

**Comment by btfou** [comment]
Supposedly supports down to IE7 with an additional js and css file. I'll include those next time.

Was thinking of you @wkeese and back compat when I included all the extra dijit icons. I'm open to suggestions on purging some of it. Was also thinking about adding some of the more generic icons like stars, camera, book, etc, but at the same time want keep the icon set simple.

It was a toss up between the solid and outline exclamation. ;) Also replaced the drop down arrow in TimeTextBox with a clock.

**Comment by wkeese** [comment]
I'm not sure that purging the real icons or placeholder icons would solve anything.  I guess I was just saying:
- don't try too hard to create the icons that aren't being used inside the dojo toolkit
- if you've got all the icons used in dijit, except for editor, at least you can claim that when documenting the theme

**Comment by btfou** [comment]
Sounds good.

I'll work on creating/adding the editor missing editor icons, and leave the leave the rest as is.

**Comment by btfou** [comment]
@dylans @wkeese Is there anything else needed to get this merged?

**Comment by wkeese** [comment]
You want to push these few icons now, and then check in the editor icons later?  I'm fine w/anything.

**Comment by dylans** [comment]
@btfou I was just waiting for you to say you're ready for review and having me land it. I should get to it tomorrow.

**Comment by btfou** [comment]
I'm happy with the icon font being cleaned up. I'm just getting started creating SVGs for fonts. Plan is to add missing editor fonts when I can.

In general, there's much which can be done to improve the theme. I'm working on a couple projects with it and will focus on improvements and fixes as I encounter issues.

**Comment by dylans** [comment]
Thanks, closed via 565be1a

**Pull request closed without merging**
