### PR TITLE
flat theme updates

### PR DESCRIPTION
**Pull request by btfou**
- fix image url
- remove bower now that not developing in `dijit/themes` directory
- add material color variables
- update buttons
- fix disabled button node borders for ComboBox, DateTextBox, etc when using alternate colors
- add Toolbar to test
- some more TODOs

### CODE REVIEW

**Comment by wkeese** [comment]
These changes seem reasonable to me.

BTW do you guys really want to check in the generated CSS files?  I agree that "bower install themes" (or however you get a built version of this code) should have the generated CSS files, but I wonder if github should have them.   The only reason dijit has the generated files is for historical reasons.

I also noticed two issues unrelated to these commits:

(1) In the color picker (both small and large), the choice for white looks weird because it's white-on-white with no border.  Compare claro:

claro

with the flat color picker:

flat

(2) The arrow directions on closed TitlePanes seems weird to me.  Typically it's a right arrow for a closed pane and a down arrow for an open pane.  Anyway, that's a matter of preference.

**Comment by kfranqueiro** [comment]
RE CSS in the repo, bower doesn't have a separate repository/storage - github _is_ its repository, so either the CSS needs to be committed here or there would need to be a build process to generate something to be committed to a separate repository.  (Though I suspect Dylan is interested in this getting built into the Dojo 1.11 release, anyway.)

Should those two issues be entered separately?

**Comment by wkeese** [comment]
Oh you are right, I forgot that bower pulls from github.  Still seems strange to check in built code into the main github repository, but I can't think of a better solution offhand.

@btfou, feel free to enter those other issues separately if you agree they are issues but don't feel like fixing them right now.

**Comment by wkeese** [comment]
PS: I can see why you don't want a border around the color squares; perhaps you should just have a border around white.

**Comment by btfou** [comment]
@wkeese I was looking at the TitlePane/Accordion pane arrows and agree closed should be right arrow. I suspect it may have been to avoid extra class for RTL. I'm going to change that up when I get back to this. This PR or next.

**Comment by dylans** [comment]
Landed what has been finished so far in master as cfab57c . @btfou will leave your next round of iterations for another PR. Thanks!

**Pull request closed without merging**
